{% set version = "0.20" %}

package:
  name: mppp
  version: {{ version }}

source:
  url: https://github.com/bluescarni/mppp/archive/v{{ version }}.tar.gz
  sha256: c736daeaac30e38e1c09a19d249209ad49f8ec92ab1315a8fb9a47cc1f54e607
  patches:
    - test_fix.diff

build:
  number: 0
  run_exports:
    # SO name changes at minor rev bumps.
    - {{ pin_subpackage('mppp', max_pin='x.x') }}
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - gmp                 # [unix]
    - libflint            # [unix]
    - arb                 # [unix]
    - mpir                # [win]
    - mpfr
  run:
    # NOTE: gmp/mpir, libflint and arb use run_exports.
    - mpfr

test:
  commands:
    - test -f $PREFIX/include/mp++/mp++.hpp               # [unix]
    - if not exist %PREFIX%\\Library\\include\\mp++\\mp++.hpp exit 1   # [win]

about:
  home: https://bluescarni.github.io/mppp/
  license: MPL-2.0
  license_file: COPYING
  summary: A modern C++ library for multiprecision arithmetic

extra:
  recipe-maintainers:
    - bluescarni
