{% set version = "0.24" %}

package:
  name: mppp
  version: {{ version }}

source:
  url: https://github.com/bluescarni/mppp/archive/v{{ version }}.tar.gz
  sha256: c84cbe38545b7f3f20688791e0a7ce4020830ed84ab6a109ab13a208745be9dc
  patches:
    - test_fix.diff

build:
  number: 0
  run_exports:
    # SO name changes at minor rev bumps.
    - {{ pin_subpackage('mppp', max_pin='x.x') }}
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make                # [unix]
  host:
    - gmp                 # [unix]
    - mpir                # [win]
    - arb
    - libflint
    - mpfr
    - mpc
    # NOTE: gmp/mpir, mpfr, mpc, libflint and arb all use run_exports.
    - boost-cpp
  run:
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}

test:
  commands:
    - test -f $PREFIX/include/mp++/mp++.hpp               # [unix]
    - if not exist %PREFIX%\\Library\\include\\mp++\\mp++.hpp exit 1   # [win]

about:
  home: https://bluescarni.github.io/mppp/
  license: MPL-2.0
  license_file: COPYING
  summary: A modern C++ library for multiprecision arithmetic

extra:
  recipe-maintainers:
    - bluescarni
