{% set version = "2.0.0" %}

package:
  name: mppp
  version: {{ version }}

source:
  url: https://github.com/bluescarni/mppp/archive/v{{ version }}.tar.gz
  sha256: 699a882b8506b2e3c555a42300ad473302bfac3d35a931898816a401ed5fc5f3

build:
  number: 4
  run_exports:
    # SO name changes at minor rev bumps.
    - {{ pin_subpackage('mppp', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make                # [unix]
  host:
    - gmp
    - libflint
    - mpfr
    - mpc
    - fmt
    - libboost-devel
    - winpthreads-devel      # [win]
  run:

test:
  commands:
    - test -f $PREFIX/include/mp++/mp++.hpp               # [unix]
    - if not exist %PREFIX%\\Library\\include\\mp++\\mp++.hpp exit 1   # [win]

about:
  home: https://bluescarni.github.io/mppp/
  license: MPL-2.0
  license_file: COPYING
  summary: A modern C++ library for multiprecision arithmetic

extra:
  recipe-maintainers:
    - bluescarni
