{% set version = "0.26" %}

package:
  name: mppp
  version: {{ version }}

source:
  url: https://github.com/bluescarni/mppp/archive/v{{ version }}.tar.gz
  sha256: 4dbfa68802d9a1365eda884f085418afc147d01b7a928e8333e4dcc1c3b3ce9e

build:
  number: 1
  run_exports:
    # SO name changes at minor rev bumps.
    - {{ pin_subpackage('mppp', max_pin='x.x') }}
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make                # [unix]
  host:
    - gmp                 # [unix]
    - mpir                # [win]
    - arb
    - libflint
    - mpfr
    - mpc
    # NOTE: gmp/mpir, mpfr, mpc, libflint and arb all use run_exports.
    - boost-cpp
  run:
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}

test:
  commands:
    - test -f $PREFIX/include/mp++/mp++.hpp               # [unix]
    - if not exist %PREFIX%\\Library\\include\\mp++\\mp++.hpp exit 1   # [win]

about:
  home: https://bluescarni.github.io/mppp/
  license: MPL-2.0
  license_file: COPYING
  summary: A modern C++ library for multiprecision arithmetic

extra:
  recipe-maintainers:
    - bluescarni
