{% set version = "0.11" %}

package:
  name: mppp
  version: {{ version }}

source:
  url: https://github.com/bluescarni/mppp/archive/v{{ version }}.tar.gz
  sha256: 07646290f483a9f0c02846514576daba9f5975115752cc4b0666097221e1b5e7

build:
  number: 1000
  skip: true   # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - gmp                 # [unix]
    - mpir                # [win]
    - mpfr
  run:
    - gmp                 # [unix]
    - mpir                # [win]
    - mpfr

test:
  commands:
    - test -f $PREFIX/include/mp++/mp++.hpp               # [unix]
    - if not exist %PREFIX%\\Library\\include\\mp++\\mp++.hpp exit 1   # [win]

about:
  home: https://bluescarni.github.io/mppp/
  license: MPL2
  license_file: COPYING
  summary: 'A modern C++ library for multiprecision arithmetic'

extra:
  recipe-maintainers:
    - bluescarni
