{% set version = "1.0.1" %}

package:
  name: mppp
  version: {{ version }}

source:
  url: https://github.com/bluescarni/mppp/archive/v{{ version }}.tar.gz
  sha256: 90e8758bad2d9ebec04305d9cc394168de7bd563acc290e273dd68467e07de07

build:
  number: 0
  run_exports:
    # SO name changes at minor rev bumps.
    - {{ pin_subpackage('mppp', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make                # [unix]
  host:
    - gmp                 # [unix]
    - mpir                # [win]
    - arb
    # NOTE: flint 3 has several breaking changes
    # that will have to be addressed upstream.
    - libflint <3
    - mpfr
    - mpc
    - fmt
    - libboost-devel
  run:

test:
  commands:
    - test -f $PREFIX/include/mp++/mp++.hpp               # [unix]
    - if not exist %PREFIX%\\Library\\include\\mp++\\mp++.hpp exit 1   # [win]

about:
  home: https://bluescarni.github.io/mppp/
  license: MPL-2.0
  license_file: COPYING
  summary: A modern C++ library for multiprecision arithmetic

extra:
  recipe-maintainers:
    - bluescarni
