{% set version = "0.17" %}

package:
  name: mppp
  version: {{ version }}

source:
  url: https://github.com/bluescarni/mppp/archive/v{{ version }}.tar.gz
  sha256: 828b1b719c915e021641c6837d537a5de0c9f6977ec5abd4046d1be1cd1de351

build:
  number: 2
  skip: true   # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - gmp                 # [unix]
    - mpir                # [win]
    - mpfr
  run:
    - gmp                 # [unix]
    - mpir                # [win]
    - mpfr

test:
  commands:
    - test -f $PREFIX/include/mp++/mp++.hpp               # [unix]
    - if not exist %PREFIX%\\Library\\include\\mp++\\mp++.hpp exit 1   # [win]

about:
  home: https://bluescarni.github.io/mppp/
  license: MPL2
  license_file: COPYING
  summary: 'A modern C++ library for multiprecision arithmetic'

extra:
  recipe-maintainers:
    - bluescarni
