{% set version = "0.21" %}

package:
  name: mppp
  version: {{ version }}

source:
  url: https://github.com/bluescarni/mppp/archive/v{{ version }}.tar.gz
  sha256: 49a05fc6874a800cb42a3ac16eb46a50583f0b59d3b54008c58af766186a8c69

build:
  number: 2
  run_exports:
    # SO name changes at minor rev bumps.
    - {{ pin_subpackage('mppp', max_pin='x.x') }}
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - gmp                 # [unix]
    - mpir                # [win]
    - arb
    - libflint
    - mpfr
    - mpc
    # NOTE: gmp/mpir, mpfr, mpc, libflint and arb all use run_exports.

test:
  commands:
    - test -f $PREFIX/include/mp++/mp++.hpp               # [unix]
    - if not exist %PREFIX%\\Library\\include\\mp++\\mp++.hpp exit 1   # [win]

about:
  home: https://bluescarni.github.io/mppp/
  license: MPL-2.0
  license_file: COPYING
  summary: A modern C++ library for multiprecision arithmetic

extra:
  recipe-maintainers:
    - bluescarni
