travis:
  secure:
    BINSTAR_TOKEN: zahkYvhZsYKQa+zDoEytySu2aicFvJL5iuaPaKVwZI/mMz6nG3zjdDlYOpzgI5qLaxL4q6ieXTVQNzzgnfJxefwuur7cad09G1CVS4cEzIHu5u/W92MerCMfFQX09A8DSvVBG/M+v1flVI/vEf3kT+RjpD3502DwVze3Anb+99lrow9vTyHepofDAKrRML8pzVZk7p9Z/WModMCm0O/AJ6C5wjvUNOHWyekAlpqBwI+jvlGPToDjyuOGL1B2aES6JzyQ0nS1wFIdXSDKlimWlVuqKSpG/TLLIaeuPa9z5b3gGR3mV+JErOJgnnxC0yoNrQko12UtiWZwI4BkNdtmb4vh1fa3MU66NWglQDGtOXqKmaCRmszoQq3l5JDlG3f6d0honSzq2L1txfEFqxvN12yy3agqEW1+IHDdO0ovEL+HvVcuQUJ8B52MMo0frSn+5kyw9hslofuWi7VMJL4hgP2xHkwL3gippXz7sKiSp1tzK7X4re9nTpJOwmbZrM3aImGMA4SZ0DVRFPvMkGk1njx9MwxrCYMqV4bUwgXdlthJ/ER531CwDLUfSqfxe2bSNxpR2PJ6EVWT+cqo1C54NzjezBTMvv8ihH9NqOt4JCPR+nITwKxJzICEnkNXRxoAGA03LpUnIuFOKeDjrYEmtlo3yDR54/9aP/xukhJ06o8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
