travis:
  secure:
    BINSTAR_TOKEN: T8G67epEEbjd2NDxA8rEmO/Z6rjzxeMLbdhpP8aEuLCL4SC6o705acKTDjuVAWpQPmPj904ldwhnYNRHNOeSHTNJTlaAxDssb7GKlQBj3iZSRxbje+l8P8Qsql1TFCJer6wS/jCVVJDBJFPVjl0AJ/XMvqyIK2sQODQHitWv1eIbdsMkBfBkbR/BRcOjlsSfDmpN6y3lPfE8eEBtBDbx5h82Wuppc2Gcvj9G8UR6S1evK5wg4KsrD+hQ9OV1/y+/BgPo5HVgcb5B0h9EQgMsKJZBLRjPBTdkzD7Wu+6f+9Tp3KWkp+VQoCl1+TwT234TH0DGQaeLcIoBhOc94s7zB4CfViUWANGF9GaxbLAcKZisLBk8BJIwO0TkfLtuN5LCCR6OabRbdS4IpxTdin+3AR/0vw3ttvWa6p27o46ylom2GmV5L135B/XYNv5eZNlGDxQgtC7adZH315fPfd5YBUF0r9HZD17tBpVvcKlyPhn4I9kCghBjKXm/QUymxSfxzKz4L3DZmsdA7QelPF8zYjHOXhFRNdSyPgvQ1Ih/MKneRlllyTm50Bca+ijlmPYPgMQjikR9J1VToD0/gvOJ1QtxHi5rtK/MBGiz0JcL84hQBVLnH6XUQd8/gzT69cXYiVS2vz4jUHsge1z1SunSuyrWasvNwBslO0gw39MMx6s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
